// Auto-generated by scripts/generateCountyPaths.mjs — do not edit
// States absent here (ri, ak, Canadian provinces) fall back to the
// list-only county picker fed by the server's /filters counties.
import type { StateKey } from '../../generated/states';

import { VIEWBOX as AL_VB, COUNTIES as AL_C } from './al';
import { VIEWBOX as AZ_VB, COUNTIES as AZ_C } from './az';
import { VIEWBOX as AR_VB, COUNTIES as AR_C } from './ar';
import { VIEWBOX as CA_VB, COUNTIES as CA_C } from './ca';
import { VIEWBOX as CO_VB, COUNTIES as CO_C } from './co';
import { VIEWBOX as CT_VB, COUNTIES as CT_C } from './ct';
import { VIEWBOX as DE_VB, COUNTIES as DE_C } from './de';
import { VIEWBOX as FL_VB, COUNTIES as FL_C } from './fl';
import { VIEWBOX as GA_VB, COUNTIES as GA_C } from './ga';
import { VIEWBOX as HI_VB, COUNTIES as HI_C } from './hi';
import { VIEWBOX as ID_VB, COUNTIES as ID_C } from './id';
import { VIEWBOX as IL_VB, COUNTIES as IL_C } from './il';
import { VIEWBOX as IN_VB, COUNTIES as IN_C } from './in';
import { VIEWBOX as IA_VB, COUNTIES as IA_C } from './ia';
import { VIEWBOX as KS_VB, COUNTIES as KS_C } from './ks';
import { VIEWBOX as KY_VB, COUNTIES as KY_C } from './ky';
import { VIEWBOX as LA_VB, COUNTIES as LA_C } from './la';
import { VIEWBOX as ME_VB, COUNTIES as ME_C } from './me';
import { VIEWBOX as MD_VB, COUNTIES as MD_C } from './md';
import { VIEWBOX as MA_VB, COUNTIES as MA_C } from './ma';
import { VIEWBOX as MI_VB, COUNTIES as MI_C } from './mi';
import { VIEWBOX as MN_VB, COUNTIES as MN_C } from './mn';
import { VIEWBOX as MS_VB, COUNTIES as MS_C } from './ms';
import { VIEWBOX as MO_VB, COUNTIES as MO_C } from './mo';
import { VIEWBOX as MT_VB, COUNTIES as MT_C } from './mt';
import { VIEWBOX as NE_VB, COUNTIES as NE_C } from './ne';
import { VIEWBOX as NV_VB, COUNTIES as NV_C } from './nv';
import { VIEWBOX as NH_VB, COUNTIES as NH_C } from './nh';
import { VIEWBOX as NJ_VB, COUNTIES as NJ_C } from './nj';
import { VIEWBOX as NM_VB, COUNTIES as NM_C } from './nm';
import { VIEWBOX as NY_VB, COUNTIES as NY_C } from './ny';
import { VIEWBOX as NC_VB, COUNTIES as NC_C } from './nc';
import { VIEWBOX as ND_VB, COUNTIES as ND_C } from './nd';
import { VIEWBOX as OH_VB, COUNTIES as OH_C } from './oh';
import { VIEWBOX as OK_VB, COUNTIES as OK_C } from './ok';
import { VIEWBOX as OR_VB, COUNTIES as OR_C } from './or';
import { VIEWBOX as PA_VB, COUNTIES as PA_C } from './pa';
import { VIEWBOX as SC_VB, COUNTIES as SC_C } from './sc';
import { VIEWBOX as SD_VB, COUNTIES as SD_C } from './sd';
import { VIEWBOX as TN_VB, COUNTIES as TN_C } from './tn';
import { VIEWBOX as TX_VB, COUNTIES as TX_C } from './tx';
import { VIEWBOX as UT_VB, COUNTIES as UT_C } from './ut';
import { VIEWBOX as VT_VB, COUNTIES as VT_C } from './vt';
import { VIEWBOX as VA_VB, COUNTIES as VA_C } from './va';
import { VIEWBOX as WA_VB, COUNTIES as WA_C } from './wa';
import { VIEWBOX as WV_VB, COUNTIES as WV_C } from './wv';
import { VIEWBOX as WI_VB, COUNTIES as WI_C } from './wi';
import { VIEWBOX as WY_VB, COUNTIES as WY_C } from './wy';

export interface CountyMapData {
  viewBox: string;
  counties: Record<string, { d: string; cx: number; cy: number }>;
}

export const COUNTY_MAPS: Partial<Record<StateKey, CountyMapData>> = {
  al: { viewBox: AL_VB, counties: AL_C },
  az: { viewBox: AZ_VB, counties: AZ_C },
  ar: { viewBox: AR_VB, counties: AR_C },
  ca: { viewBox: CA_VB, counties: CA_C },
  co: { viewBox: CO_VB, counties: CO_C },
  ct: { viewBox: CT_VB, counties: CT_C },
  de: { viewBox: DE_VB, counties: DE_C },
  fl: { viewBox: FL_VB, counties: FL_C },
  ga: { viewBox: GA_VB, counties: GA_C },
  hi: { viewBox: HI_VB, counties: HI_C },
  id: { viewBox: ID_VB, counties: ID_C },
  il: { viewBox: IL_VB, counties: IL_C },
  in: { viewBox: IN_VB, counties: IN_C },
  ia: { viewBox: IA_VB, counties: IA_C },
  ks: { viewBox: KS_VB, counties: KS_C },
  ky: { viewBox: KY_VB, counties: KY_C },
  la: { viewBox: LA_VB, counties: LA_C },
  me: { viewBox: ME_VB, counties: ME_C },
  md: { viewBox: MD_VB, counties: MD_C },
  ma: { viewBox: MA_VB, counties: MA_C },
  mi: { viewBox: MI_VB, counties: MI_C },
  mn: { viewBox: MN_VB, counties: MN_C },
  ms: { viewBox: MS_VB, counties: MS_C },
  mo: { viewBox: MO_VB, counties: MO_C },
  mt: { viewBox: MT_VB, counties: MT_C },
  ne: { viewBox: NE_VB, counties: NE_C },
  nv: { viewBox: NV_VB, counties: NV_C },
  nh: { viewBox: NH_VB, counties: NH_C },
  nj: { viewBox: NJ_VB, counties: NJ_C },
  nm: { viewBox: NM_VB, counties: NM_C },
  ny: { viewBox: NY_VB, counties: NY_C },
  nc: { viewBox: NC_VB, counties: NC_C },
  nd: { viewBox: ND_VB, counties: ND_C },
  oh: { viewBox: OH_VB, counties: OH_C },
  ok: { viewBox: OK_VB, counties: OK_C },
  or: { viewBox: OR_VB, counties: OR_C },
  pa: { viewBox: PA_VB, counties: PA_C },
  sc: { viewBox: SC_VB, counties: SC_C },
  sd: { viewBox: SD_VB, counties: SD_C },
  tn: { viewBox: TN_VB, counties: TN_C },
  tx: { viewBox: TX_VB, counties: TX_C },
  ut: { viewBox: UT_VB, counties: UT_C },
  vt: { viewBox: VT_VB, counties: VT_C },
  va: { viewBox: VA_VB, counties: VA_C },
  wa: { viewBox: WA_VB, counties: WA_C },
  wv: { viewBox: WV_VB, counties: WV_C },
  wi: { viewBox: WI_VB, counties: WI_C },
  wy: { viewBox: WY_VB, counties: WY_C },
};
