// generateStatePaths.mjs — generate the US + Canada state/province map for
// the StateSelectScreen map picker.
//
//   node scripts/generateStatePaths.mjs
//
// Source: Natural Earth 1:50m admin-1 states/provinces (unprojected lon/lat;
// one source for both countries so the shared border aligns). Projection:
// Albers-style conic equal-area centered on North America, so Alaska sits in
// place next to Yukon. Hawaii is re-projected into an inset box at the
// bottom-left (standard atlas treatment — a true-position Hawaii would drag
// the whole map's scale down).
//
// Every feature is emitted; `key` is the LakeLore StateKey when the
// state/province is in the registry, or null for places without data
// (DC, Puerto Rico, Yukon/NWT/Nunavut, Atlantic provinces) — the picker
// renders those muted and non-selectable.
import { geoConicEqualArea, geoPath, geoCentroid } from 'd3-geo';
import fs from 'fs';
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.join(__dirname, '../src/data/statePaths.ts');
const CACHE = path.join(os.tmpdir(), 'ne_50m_admin_1.json');
const SRC_URL = 'https://raw.githubusercontent.com/martynafford/natural-earth-geojson/master/50m/cultural/ne_50m_admin_1_states_provinces.json';

// Registry keys (mirror of generated/states.ts) — which admin-1 postals are
// selectable. Kept as a literal so this script has no TS imports.
const REGISTRY_KEYS = new Set([
  'mn','sd','nd','ia','ne','wi','mi','wa','mt','ks','mo','il','in','oh','fl',
  'ga','al','tn','sc','ky','nc','va','or','id','wy','ut','co','az','nm','nv',
  'ca','ok','tx','ny','pa','ar','la','me','ma','ct','de','md','nh','ak','ms',
  'ri','wv','vt','on','hi','nj','bc','qc','mb','sk','ab',
]);

async function load() {
  if (fs.existsSync(CACHE)) return JSON.parse(fs.readFileSync(CACHE, 'utf8'));
  console.log('Fetching Natural Earth admin-1 GeoJSON…');
  const res = await fetch(SRC_URL);
  const json = await res.json();
  fs.writeFileSync(CACHE, JSON.stringify(json));
  return json;
}

const geo = await load();
const features = geo.features.filter(f => ['US', 'CA'].includes(f.properties.iso_a2));

const isHI = f => f.properties.postal === 'HI' && f.properties.iso_a2 === 'US';
const mainland = { type: 'FeatureCollection', features: features.filter(f => !isHI(f)) };

// ── Mainland: Albers-ish conic over North America ────────────────────────────
const W = 500, PAD = 4;
const probeH = 500;
const makeProj = (w, h) => geoConicEqualArea()
  .rotate([100, 0])
  .parallels([35, 65])
  .fitExtent([[PAD, PAD], [w - PAD, h - PAD]], mainland);

// First pass to learn the aspect, second pass into a tight box.
const probe = makeProj(W, probeH);
const [[bx0, by0], [bx1, by1]] = geoPath().projection(probe).bounds(mainland);
const H = Math.round((by1 - by0) / (bx1 - bx0) * W) + PAD * 2;
const projection = makeProj(W, H);
const pathGen = geoPath().projection(projection);

// ── Hawaii inset (bottom-left) ───────────────────────────────────────────────
// The NE geometry includes the long northwestern atoll chain (Nihoa→Kure),
// which would shrink the eight main islands to specks — drop polygons west
// of Niihau before fitting, but keep the full geometry for the drawn path.
const hiFeature = features.find(isHI);
const hiMain = {
  type: 'Feature',
  geometry: {
    type: 'MultiPolygon',
    coordinates: hiFeature.geometry.coordinates.filter(poly =>
      poly[0].some(([lon]) => lon > -160.5)),
  },
  properties: hiFeature.properties,
};
const HI_BOX = [[12, H - 74], [86, H - 12]];
const hiProj = geoConicEqualArea().rotate([157, 0]).parallels([19, 22])
  .fitExtent(HI_BOX, hiMain);
const hiPath = geoPath().projection(hiProj);

const rows = [];
for (const f of features) {
  const postal = String(f.properties.postal || '').toLowerCase();
  const key = REGISTRY_KEYS.has(postal) ? postal : null;
  const pg = isHI(f) ? hiPath : pathGen;
  const proj = isHI(f) ? hiProj : projection;
  const d = pg(isHI(f) ? hiMain : f);
  if (!d) continue;
  const centroid = proj(geoCentroid(isHI(f) ? hiMain : f));
  rows.push({
    postal: f.properties.postal,
    name: f.properties.name,
    country: f.properties.iso_a2,
    key,
    d,
    cx: Math.round(centroid[0] * 10) / 10,
    cy: Math.round(centroid[1] * 10) / 10,
  });
}

// Alaska's centroid lands mid-panhandle because of the Aleutians; nudge it
// onto the mainland so the label + tap target sit where users expect.
const akRow = rows.find(r => r.postal === 'AK' && r.country === 'US');
if (akRow) { akRow.cx += 28; akRow.cy -= 10; }

let ts = `// Auto-generated by scripts/generateStatePaths.mjs — do not edit\n`;
ts += `// US states + Canadian provinces, conic equal-area over North America,\n`;
ts += `// Hawaii inset bottom-left. key=null → no LakeLore data (render muted).\n`;
ts += `import type { StateKey } from '../generated/states';\n\n`;
ts += `export const STATES_VIEWBOX = '0 0 ${W} ${H}';\n\n`;
ts += `export interface StatePathDatum {\n  postal: string;\n  name: string;\n  country: 'US' | 'CA';\n  key: StateKey | null;\n  d: string;\n  cx: number;\n  cy: number;\n}\n\n`;
ts += `export const STATE_PATHS: StatePathDatum[] = ${JSON.stringify(rows, null, 1)};\n`;
fs.writeFileSync(OUT_PATH, ts);
console.log(`wrote ${OUT_PATH}: ${rows.length} features (${rows.filter(r => r.key).length} selectable), viewBox 0 0 ${W} ${H}`);
